AWSTemplateFormatVersion: "2010-09-09"
Description: ALB invoking Lambda function

Parameters:
  VpcId:
    Type: String
    Default: vpc-00e2430245457380c  # ← Replace this
    Description: The VPC ID to launch the ALB into

  Subnet1:
    Type: String
    Default: subnet-021a62e1ff2bf4b47  # ← Replace this
    Description: Public Subnet 1 for ALB

  Subnet2:
    Type: String
    Default: subnet-08f9b1c2e00d4ae07  # ← Replace this
    Description: Public Subnet 2 for ALB

Resources:

  # IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaAlbDemoRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # Lambda Function
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ALBToLambdaFunction
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          def handler(event, context):
              print(event)
              html_content = """
              <html>
                <head>
                  <title>Welcome</title>
                  <style>
                    body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; }
                    h1 { color: #2c3e50; }
                    p { color: #34495e; }
                  </style>
                </head>
                <body>
                  <h1>Hello from Lambda via ALB!</h1>
                  <p>This HTML page was served by an AWS Lambda function behind an Application Load Balancer.</p>
                </body>
              </html>
              """
              return {
                  "statusCode": 200,
                  "statusDescription": "200 OK",
                  "isBase64Encoded": False,
                  "headers": {
                      "Content-Type": "text/html"
                  },
                  "body": html_content
              }

  # ALB Security Group
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  # ALB
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: ALBForLambda
      Scheme: internet-facing
      Subnets:
        - !Ref Subnet1
        - !Ref Subnet2
      SecurityGroups:
        - !Ref ALBSecurityGroup

  # Lambda Target Group
  LambdaTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: LambdaInvokePermission
    Properties:
      Name: LambdaTargetGroup
      TargetType: lambda
      Targets:
        - Id: !GetAtt MyLambdaFunction.Arn

  # Listener
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref LambdaTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  # Permission for ALB to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: elasticloadbalancing.amazonaws.com
      SourceArn: !Sub arn:aws:elasticloadbalancing:${AWS::Region}:${AWS::AccountId}:targetgroup/LambdaTargetGroup/*


Outputs:
  ALBURL:
    Description: "Application Load Balancer DNS Name"
    Value: !GetAtt ApplicationLoadBalancer.DNSName
